In [189]:
import pandas as pd
import numpy as np
import sys, os
from importlib import reload
import yaml
from pathlib import Path
from dataclasses import asdict

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'src')))
from analysis import plots
import analysis.report
import training.gbm_model_trainer
from training.gbm_model_trainer import GBMModelTrainerConfig 

reload(analysis)
reload(analysis.plots)
reload(analysis.report)
reload(training.gbm_model_trainer)

## Load data

In [190]:
df = pd.read_csv("../data/bank-full.csv", delimiter=';')

In [191]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [192]:
# Convert 'y' to numeric for analysis
df["target"] = np.where(df["y"] == "no", 0, 1)

# Add weights to test weight parameter across functions 
df["weights"] = np.abs(np.random.randn(len(df.index)))

# Add an arbitrary data split for testing functions (TVH = 40/30/30)
df["random"] = np.random.uniform(0, 1, len(df.index))
df["split"] = np.where(
    df["random"]  > 0.70, 
    "V",
    np.where(
        df["random"]  > 0.40, 
        "H", 
        "T"
    )
)

In [193]:
df["split"].value_counts(dropna=False, normalize=True)

split
T    0.399704
H    0.301121
V    0.299175
Name: proportion, dtype: float64

In [194]:
df.groupby("split")["target"].mean()

split
H    0.117232
T    0.111283
V    0.124353
Name: target, dtype: float64

In [195]:
# Split data; define features and target
train = df.query("split == 'T'").drop(columns=["y", "split"])
test = df.query("split == 'V'").drop(columns=["y", "split"])
holdout = df.query("split == 'H'").drop(columns=["y", "split"])

## Use ModelTrainer class for training
- Can use example config files in `analysis-tools/examples` or create a config within your notebook and save it locally

In [ ]:
# Define your config
from training.gbm_model_trainer import TrainingConfig, EvaluationConfig, TuningConfig  

config = TrainingConfig(
    # Training parameters
    actual_col="target",
    predicted_col="pred_xgb",
    output_dir="outputs",
    log_file="training.log",
    model_file="model_obj.json",

    hyperparameters={
        "objective": "binary:logistic",
        "n_estimators": 100,
        "max_depth": 3,
        "learning_rate": 0.1,
        "subsample": 0.5,
        "colsample_bytree": 0.5,
        "random_state": 42,
    },

    feval="logloss",
    output_log=True,
    base_margin_col=None,

    # Logging and early stopping
    log_eval_period=50,
    early_stopping_rounds=20,
    early_stopping_metric="logloss",
    early_stopping_maximize=False,

    # Evaluation and reporting
    evaluation=EvaluationConfig(
        output_report=True,
        report_file="model_analysis.html",
        report_params={},
        tabulate_vars=["job", "education", "age"],
        plots_to_add=[
            {"plot": "gain_curve_with_gini", "title": "Gain Curve / Lorenz Curve"},
            {
                "plot": "partial_gini_plot",
                "title": "Partial Gini (Top 15%)",
                "kwargs": {"top_percent": 15},
            },
            {"plot": "lift_chart", "title": "Lift Chart"},
            {"plot": "crunched_residual_plot", "title": "Crunched Residuals"},
            {
                "plot": "plot_residual_fit",
                "title": "Std and Avg of Normalized Residuals",
                "kwargs": {"residual_type": "normalized"},
            },
        ]
    ),

    # Tuning setup
    tuning=TuningConfig(
        search_space={
            "max_depth": [3, 6],
            "eta": {"type": "real", "low": 0.01, "high": 0.3},
            "subsample": [0.6, 0.9],
        },
        n_iter=25,
        output_tuning=True,
        tuning_file="tuning_results.csv",
    )
)

# Output config to YAML
config_output_path = Path("../examples/example_config.yaml")

import yaml
# Write config to YAML file
with config_output_path.open("w") as f:
    yaml.dump(asdict(config), f, indent=2)

print(f"Config saved to {config_output_path.resolve()}")

Config saved to C:\Users\ASacco\OneDrive - Plymouth Rock Assurance Corp\repos\analysis-tools\examples\example_config.yaml

In [298]:
reload(training.gbm_model_trainer)
reload(analysis.report)
reload(analysis.plots)
from scoring import callbacks, scorers
reload(callbacks)
reload(scorers)

In [ ]:
from training.gbm_model_trainer import XGBModelTrainer

mt_xgboost = XGBModelTrainer(
    config_path="../examples/example_config.yaml",
    train_df=train,
    valid_df=test,
    holdout_df=holdout
)

In [275]:
config.evaluation

EvaluationConfig(output_report=True, report_file='model_analysis.html', report_params={}, plots_to_add=[{'plot': 'gain_curve_with_gini', 'title': 'Gain Curve / Lorenz Curve'}, {'plot': 'partial_gini_plot', 'title': 'Partial Gini (Top 15%)', 'kwargs': {'top_percent': 15}}, {'plot': 'lift_chart', 'title': 'Lift Chart'}, {'plot': 'crunched_residual_plot', 'title': 'Crunched Residuals'}, {'plot': 'plot_residual_fit', 'title': 'Std and Avg of Normalized Residuals', 'kwargs': {'residual_type': 'normalized'}}], tabulate_vars=['job', 'education', 'age'])

In [301]:
mt_xgboost.train()

In [302]:
mt_xgboost.evaluate()

c:\Users\ASacco\OneDrive - Plymouth Rock Assurance Corp\repos\analysis-tools\src\analysis\plots.py:636: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
c:\Users\ASacco\OneDrive - Plymouth Rock Assurance Corp\repos\analysis-tools\src\analysis\plots.py:636: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
c:\Users\ASacco\OneDrive - Plymouth Rock Assurance Corp\repos\analysis-tools\src\analysis\plots.py:636: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

Analysis report generated at outputs\model_analysis.html

In [303]:
mt_xgboost.tune()

         eta  max_depth  subsample     score
0   0.010439          6   0.832172 -0.860385
1   0.010000          5   0.817273 -0.859705
2   0.010000          5   0.824249 -0.859506
3   0.026925          6   0.899865 -0.858281
4   0.246533          5   0.780017 -0.858210
5   0.276225          5   0.899919 -0.857416
6   0.024278          6   0.894775 -0.857127
7   0.142513          5   0.885358 -0.856833
8   0.018127          6   0.766198 -0.856286
9   0.268688          4   0.787404 -0.856020
10  0.286925          6   0.897305 -0.855907
11  0.286888          6   0.825688 -0.855693
12  0.010000          5   0.846686 -0.855619
13  0.068624          4   0.868871 -0.854448
14  0.139121          6   0.600483 -0.853824
15  0.047460          4   0.747683 -0.853716
16  0.297602          4   0.899105 -0.853268
17  0.069581          4   0.813597 -0.852790
18  0.051837          5   0.600370 -0.852616
19  0.293214          5   0.712645 -0.852541
20  0.042691          6   0.645786 -0.851009
21  0.286934          4   0.600460 -0.850327
22  0.125053          3   0.627847 -0.846924
23  0.248353          3   0.900000 -0.845581
24  0.290726          3   0.753297 -0.845002

In [304]:
mt_xgboost.log_lines

['2025-07-31 15:07:27,752 [INFO] ---------------------------------------------------------------------------',
 '2025-07-31 15:07:27,752 [INFO] BEGINNING MODEL EVALUATION',
 '2025-07-31 15:07:31,960 [INFO] ---------------------------------------------------------------------------',
 '2025-07-31 15:07:31,960 [INFO] BEGINNING MODEL TRAINING',
 '2025-07-31 15:07:31,994 [INFO] [0] validation-logloss: 0.34891',
 '2025-07-31 15:07:32,064 [INFO] [50] validation-logloss: 0.23257',
 '2025-07-31 15:07:32,115 [INFO] Training completed in 0.1546 seconds',
 '2025-07-31 15:07:32,116 [INFO] Model: XGBoost Booster',
 "2025-07-31 15:07:32,116 [INFO] Hyperparameters: {'colsample_bytree': 0.5, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'objective': 'binary:logistic', 'random_state': 42, 'subsample': 0.5}",
 '2025-07-31 15:07:32,116 [INFO] Training data shape: (18071, 19)',
 '2025-07-31 15:07:32,116 [INFO] Validation data shape: (13526, 19)',
 '2025-07-31 15:07:32,116 [INFO] Number of predictors: 18',
 "2025-07-31 15:07:32,116 [INFO] Target column: 'target'",
 "2025-07-31 15:07:32,116 [INFO] Prediction column: 'pred_xgb'",
 '2025-07-31 15:07:32,123 [INFO] Model saved to C:\\Users\\ASacco\\OneDrive - Plymouth Rock Assurance Corp\\repos\\analysis-tools\\notebooks\\outputs\\model_obj.json',
 '2025-07-31 15:07:32,126 [INFO] Saved config to outputs\\config.yaml',
 '2025-07-31 15:07:32,746 [INFO] ---------------------------------------------------------------------------',
 '2025-07-31 15:07:32,747 [INFO] BEGINNING MODEL EVALUATION',
 '2025-07-31 15:07:33,348 [INFO] Added plot: Gain Curve / Lorenz Curve (gain_curve_with_gini)',
 '2025-07-31 15:07:33,721 [INFO] Added plot: Partial Gini (Top 15%) (partial_gini_plot)',
 '2025-07-31 15:07:33,982 [INFO] Added plot: Lift Chart (lift_chart)',
 '2025-07-31 15:07:34,247 [INFO] Added plot: Crunched Residuals (crunched_residual_plot)',
 '2025-07-31 15:07:34,712 [INFO] Added plot: Std and Avg of Normalized Residuals (plot_residual_fit)',
 '2025-07-31 15:07:34,722 [INFO] Analysis report saved to C:\\Users\\ASacco\\OneDrive - Plymouth Rock Assurance Corp\\repos\\analysis-tools\\notebooks\\outputs\\model_analysis.html',
 '2025-07-31 15:07:36,759 [INFO] ---------------------------------------------------------------------------',
 '2025-07-31 15:07:36,760 [INFO] BEGINNING BAYESIAN HYPERPARAMETER TUNING',
 '2025-07-31 15:07:36,800 [INFO] [0] validation-logloss: 0.34820',
 '2025-07-31 15:07:36,899 [INFO] [50] validation-logloss: 0.22314',
 "2025-07-31 15:07:36,990 [INFO] Trial 1: score=-0.85629 params={'eta': 0.01812702988146324, 'max_depth': np.int64(6), 'subsample': 0.766197707040566}",
 '2025-07-31 15:07:37,006 [INFO] [0] validation-logloss: 0.34844',
 '2025-07-31 15:07:37,091 [INFO] [50] validation-logloss: 0.22286',
 "2025-07-31 15:07:37,181 [INFO] Trial 2: score=-0.85821 params={'eta': 0.2465325981320531, 'max_depth': np.int64(5), 'subsample': 0.7800165104972226}",
 '2025-07-31 15:07:37,197 [INFO] [0] validation-logloss: 0.34738',
 '2025-07-31 15:07:37,255 [INFO] [50] validation-logloss: 0.22404',
 "2025-07-31 15:07:37,329 [INFO] Trial 3: score=-0.85445 params={'eta': 0.06862435423991252, 'max_depth': np.int64(4), 'subsample': 0.8688714098728338}",
 '2025-07-31 15:07:37,345 [INFO] [0] validation-logloss: 0.34706',
 '2025-07-31 15:07:37,391 [INFO] [50] validation-logloss: 0.22524',
 "2025-07-31 15:07:37,458 [INFO] Trial 4: score=-0.85372 params={'eta': 0.04745991252708635, 'max_depth': np.int64(4), 'subsample': 0.7476826773797134}",
 '2025-07-31 15:07:37,472 [INFO] [0] validation-logloss: 0.34940',
 '2025-07-31 15:07:37,534 [INFO] [50] validation-logloss: 0.23165',
 "2025-07-31 15:07:37,587 [INFO] Trial 5: score=-0.84692 params={'eta': 0.12505324652002878, 'max_depth': np.int64(3), 'subsample': 0.6278469324733864}",
 '2025-07-31 15:07:37,604 [INFO] [0] validation-logloss: 0.34729',
 '2025-07-31 15:07:37,653 [INFO] [50] validation-logloss: 0.22519',
 "2025-07-31 15:07:37,741 [INFO] Trial 6: score=-0.85279 params={'eta': 0.06958067859979214, 'max_depth': np.int64(4), 'subsample': 0.8135973308956965}",
 '2025-07-31 15:07:37,758 [INFO] [0] validation-logloss: 0.34884',
 '2025-07-31 15:07:37,831 [INFO] [50] validation-logloss: 0.22435',
 "2025-07-31 15:07:37,944 [INFO] Trial 7: score=-0.85101 params={'eta': 0.04269142170596584, 'max_depth': np.int64(6), 'subsample': 0.6457864099849855}",
 '2025-07-31 15:07:37,960 [INFO] [0] validation-logloss: 0.34879',
 '2025-07-31 15:07:38,018 [INFO] [50] validation-logloss: 0.22472',
 "2025-07-31 15:07:38,135 [INFO] Trial 8: score=-0.85262 params={'eta': 0.05183670349777616, 'max_depth': np.int64(5), 'subsample': 0.6003702481439113}",
 '2025-07-31 15:07:38,155 [INFO] [0] validation-logloss: 0.35311',
 '2025-07-31 15:07:38,218 [INFO] [50] validation-logloss: 0.22303',
 "2025-07-31 15:07:38,314 [INFO] Trial 9: score=-0.85683 params={'eta': 0.14251260785133096, 'max_depth': np.int64(5), 'subsample': 0.8853575089879949}",
 '2025-07-31 15:07:38,330 [INFO] [0] validation-logloss: 0.34740',
 '2025-07-31 15:07:38,388 [INFO] [50] validation-logloss: 0.22493',
 "2025-07-31 15:07:38,458 [INFO] Trial 10: score=-0.85602 params={'eta': 0.2686883853543249, 'max_depth': np.int64(4), 'subsample': 0.787404082738077}",
 '2025-07-31 15:07:38,610 [INFO] [0] validation-logloss: 0.34962',
 '2025-07-31 15:07:38,659 [INFO] [50] validation-logloss: 0.23206',
 "2025-07-31 15:07:38,736 [INFO] Trial 11: score=-0.84558 params={'eta': 0.2483530577306782, 'max_depth': np.int64(3), 'subsample': 0.9}",
 '2025-07-31 15:07:38,891 [INFO] [0] validation-logloss: 0.35246',
 '2025-07-31 15:07:38,977 [INFO] [50] validation-logloss: 0.22088',
 "2025-07-31 15:07:39,129 [INFO] Trial 12: score=-0.85591 params={'eta': 0.2869254757369441, 'max_depth': np.int64(6), 'subsample': 0.897304707877014}",
 '2025-07-31 15:07:39,354 [INFO] [0] validation-logloss: 0.34754',
 '2025-07-31 15:07:39,464 [INFO] [50] validation-logloss: 0.22709',
 "2025-07-31 15:07:39,596 [INFO] Trial 13: score=-0.85033 params={'eta': 0.28693429440203244, 'max_depth': np.int64(4), 'subsample': 0.6004600250277304}",
 '2025-07-31 15:07:39,795 [INFO] [0] validation-logloss: 0.35316',
 '2025-07-31 15:07:39,897 [INFO] [50] validation-logloss: 0.22252',
 "2025-07-31 15:07:40,030 [INFO] Trial 14: score=-0.85742 params={'eta': 0.2762246777078621, 'max_depth': np.int64(5), 'subsample': 0.8999190025464671}",
 '2025-07-31 15:07:40,267 [INFO] [0] validation-logloss: 0.35245',
 '2025-07-31 15:07:40,374 [INFO] [50] validation-logloss: 0.22158',
 "2025-07-31 15:07:40,523 [INFO] Trial 15: score=-0.85828 params={'eta': 0.026924565616885318, 'max_depth': np.int64(6), 'subsample': 0.8998645224926292}",
 '2025-07-31 15:07:40,858 [INFO] [0] validation-logloss: 0.34881',
 '2025-07-31 15:07:40,938 [INFO] [50] validation-logloss: 0.22180',
 "2025-07-31 15:07:41,047 [INFO] Trial 16: score=-0.85951 params={'eta': 0.01, 'max_depth': np.int64(5), 'subsample': 0.8242486100192741}",
 '2025-07-31 15:07:41,329 [INFO] [0] validation-logloss: 0.34861',
 '2025-07-31 15:07:41,403 [INFO] [50] validation-logloss: 0.22238',
 "2025-07-31 15:07:41,499 [INFO] Trial 17: score=-0.85971 params={'eta': 0.01, 'max_depth': np.int64(5), 'subsample': 0.8172732350292576}",
 '2025-07-31 15:07:41,759 [INFO] [0] validation-logloss: 0.34627',
 '2025-07-31 15:07:41,831 [INFO] [50] validation-logloss: 0.22524',
 "2025-07-31 15:07:41,930 [INFO] Trial 18: score=-0.85254 params={'eta': 0.2932140014393622, 'max_depth': np.int64(5), 'subsample': 0.7126451681253831}",
 '2025-07-31 15:07:42,192 [INFO] [0] validation-logloss: 0.34815',
 '2025-07-31 15:07:42,293 [INFO] [50] validation-logloss: 0.22172',
 "2025-07-31 15:07:42,426 [INFO] Trial 19: score=-0.86038 params={'eta': 0.01043872417410456, 'max_depth': np.int64(6), 'subsample': 0.8321724843392732}",
 '2025-07-31 15:07:42,692 [INFO] [0] validation-logloss: 0.34953',
 '2025-07-31 15:07:42,742 [INFO] [50] validation-logloss: 0.23153',
 "2025-07-31 15:07:42,810 [INFO] Trial 20: score=-0.84500 params={'eta': 0.2907259987478008, 'max_depth': np.int64(3), 'subsample': 0.7532967574230588}",
 '2025-07-31 15:07:43,058 [INFO] [0] validation-logloss: 0.34858',
 '2025-07-31 15:07:43,144 [INFO] [50] validation-logloss: 0.22454',
 "2025-07-31 15:07:43,269 [INFO] Trial 21: score=-0.85382 params={'eta': 0.1391207803040358, 'max_depth': np.int64(6), 'subsample': 0.6004828454273937}",
 '2025-07-31 15:07:43,505 [INFO] [0] validation-logloss: 0.34816',
 '2025-07-31 15:07:43,588 [INFO] [50] validation-logloss: 0.22225',
 "2025-07-31 15:07:43,692 [INFO] Trial 22: score=-0.85569 params={'eta': 0.28688814856072453, 'max_depth': np.int64(6), 'subsample': 0.825688056044198}",
 '2025-07-31 15:07:43,920 [INFO] [0] validation-logloss: 0.34838',
 '2025-07-31 15:07:43,984 [INFO] [50] validation-logloss: 0.22255',
 "2025-07-31 15:07:44,080 [INFO] Trial 23: score=-0.85562 params={'eta': 0.01, 'max_depth': np.int64(5), 'subsample': 0.8466857849782989}",
 '2025-07-31 15:07:44,306 [INFO] [0] validation-logloss: 0.35251',
 '2025-07-31 15:07:44,392 [INFO] [50] validation-logloss: 0.22135',
 "2025-07-31 15:07:44,501 [INFO] Trial 24: score=-0.85713 params={'eta': 0.024278261834633066, 'max_depth': np.int64(6), 'subsample': 0.894775097541902}",
 '2025-07-31 15:07:44,717 [INFO] [0] validation-logloss: 0.34759',
 '2025-07-31 15:07:44,773 [INFO] [50] validation-logloss: 0.22380',
 "2025-07-31 15:07:44,851 [INFO] Trial 25: score=-0.85327 params={'eta': 0.29760172272491037, 'max_depth': np.int64(4), 'subsample': 0.8991052360013705}",
 '2025-07-31 15:07:45,069 [INFO] Tuning DF saved to C:\\Users\\ASacco\\OneDrive - Plymouth Rock Assurance Corp\\repos\\analysis-tools\\notebooks\\outputs\\tuning_results.csv']

## Test Hyperparameter tuning